version: 0.0.0.{build}
configuration: Release
platform: Any CPU
os: Visual Studio 2017
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- cmd: dotnet restore
build:
    project: Stranne.BooliLib.sln
    verbosity: quiet